### ISSUE TITLE
Please create new tag 1.1.0 

### ISSUE THREAD

**Issue by iNono22** [sobri909/MGEvents#2]
@sobri909 
Please create new tag 1.1.0 because MGBoxKit install the last release witch is tag on 1.0.3

**Comment by sobri909** [comment]
Apologies for the late reply. I've been working on a Swift project so haven't been keeping an eye on Objective-C things lately [aside: I have been using MGEvents nicely in Swift though, ~~with one minor change, to work around a Swift compiler bug~~].

It looks like @staminajim prepped for a 1.1.0 release but didn't follow through. James, any reason for that?

Oh, it looks like 1.0.3 also predates a whole bunch of other feature additions. K, unless @staminajim objects I'll prep and ship a 1.1.0 release. Though I wonder if one of the changes might have broken backwards compat, so it might have to be a 2.0.0. Anyway, one way or another I'll ship a new release shortly. 

Thanks for the heads up @arnaudWasappli!

**Comment by sobri909** [comment]
Okay, I've pushed a 1.1.0 release now. Yay!
